state: RI

links:
- name: primary
  url: https://ri-department-of-health-covid-19-vaccine-data-rihealth.hub.arcgis.com
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(60000);
    page.done();
  message: waiting for RI vaccine data dash

- name: secondary
  url: https://datastudio.google.com/u/0/reporting/d8e4680b-7cf1-4a70-860b-7bbf5e0bf9a2/page/D0DYC
  message: alternative view of breakthrough infections data in case the dash (secondary) does not load
