state: US

links:
- name: breakthrough_cases
  url: https://www.cdc.gov/vaccines/covid-19/health-departments/breakthrough-cases.html

- name: cases_by_vax_status
  url: https://covid.cdc.gov/covid-data-tracker/#rates-by-vaccine-status
  overseerScript: |
    page.manualWait();
    await page.waitForDelay(15000);
    page.done();
  
- name: cases_or_deaths_by_age_and_vax_status
  url: https://data.cdc.gov/api/views/3rge-nu2a/rows.csv?accessType=DOWNLOAD
  file: csv
